server:
  port: 9191

spring:
  application:
    name: GateWay

  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**
        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/order/**

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost